### PR TITLE
add MCP server badge

### PR DESCRIPTION
**Pull request by punkpeye**
This PR adds a badge for the mcp-miro server listing in Glama MCP server directory.

https://glama.ai/mcp/servers/gr5t7vthv3

Glama performs regular codebase and documentation scans to:

* Confirm that the MCP server is working as expected
* Confirm that there are no obvious security issues with dependencies of the server
* Extract server characteristics such as tools, resources, prompts, and required parameters.

This badge helps your users to quickly asses that the MCP server is safe, server capabilities, and instructions for installing the server.

### CODE REVIEW

**Comment by punkpeye** [comment]
@evalstate As for your question, I will add a FAQ section to the bottom of every server that details how we do it.

The short version is that I am building Docker images and using LLMs to setup the projects, run them, and inspect the codebase. The checks are done every 6 hours and a new analyzes is performed every time changes are found.

For security, we are using https://socket.dev/ to scan the repo.

Still a young project, but I think we are the furthest ahead in this space.

**Comment by evalstate** [comment]
Thanks - that's a brilliant initiative - happy to support it for a number of different reasons. 

It would be quite cool if it would also look at a branch of the repo (some kind of pre-publish flow) as it sounds like your system may pick things up other parts of the build process might miss. 

Happy to participate, just let me know. Best.

**Comment by punkpeye** [comment]
> Thanks - that's a brilliant initiative - happy to support it for a number of different reasons.
> 
> It would be quite cool if it would also look at a branch of the repo (some kind of pre-publish flow) as it sounds like your system may pick things up other parts of the build process might miss.
> 
> Happy to participate, just let me know. Best.

Are you on Discord?

I am on https://glama.ai/mcp/discord

**Comment by evalstate** [comment]
I'll head over that way a bit later :)

**Comment by punkpeye** [comment]
Let me know your Discord username and I will give you a special flair that's only for MCP server authors.

**Pull request merged**
